### ISSUE TITLE
What is Python interpreter

### ISSUE THREAD

**Issue by surjyaneeh** [surjyaneeh/Pyberry#3]
### Description :
What is a Python interpreter ?
How does it work?

### Note :
Changes should be made inside the Python/ directory & Python branch.
Issue will be assigned on a first come first serve basis, 1 Issue == 1 PR.
In the PR, keep this issue's title as your PR's title.

**Comment by BhaswatiRoy** [comment]
I would like to contribute on audio portion of this issue
